### ISSUE TITLE
Training process for this project

### ISSUE THREAD

**Issue by williamlee91** [shamanez/Self-Supervised-Embedding-Fusion-Transformer#1]
Hi, siriwardhana. Could you introduce this project more explicitly including pre-process for raw, label assignment and division into three parts(train, valid, test). Thanks

**Comment by shamanez** [comment]
Hi, I used the CMU-MOSI SDK to get the labels. 

https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/141

[This script](https://github.com/shamanez/Self-Supervised-Embedding-Fusion-Transformer/blob/master/emotion_data_preprocessing.py) will help you to clean the multimodal raw data.
